version: "3.8"
networks:
  loki:

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    volumes:
      - lokidada:/loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

  auction-svc:
    build:
      context: ..
      dockerfile: dockerfile
    image: caspfh/auction-serviceapi:latest
    ports:
      - "5230:8082"
    expose: 
      - "8082"
    environment:
    - server="localhost"
    - port="27017"
    - database="AuctionDB"
    - collection="auctionBidCol"
    - rabbitMQPort="5672"
    - redisConnection="redis-16065.c56.east-us.azure.redns.redis-cloud.com:16065,password=1234"
    - Secret="RasmusGrønErSuperCoolOgDenBedsteChef!"
    - Issuer="Gron&OlsenGruppen"

    networks:
      - loki
    depends_on:
      - loki

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auction-svc
    ports:
      - "4200:4200"
    networks:
      - loki

  mongodb:
    image: mongo:latest
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27018:27017"
    networks: 
      - loki

  rabbitmq-service:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
    expose:
      - "8080"
    networks:
      - default

  redis-service:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    expose:
      - "8080"
    networks:
      - default

volumes:
  mongodbdata:
  lokidada: